ci: test output
Signed-off-by: Callahan Kovacs <callahan.kovacs@canonical.com>

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -33,8 +33,6 @@ jobs:
     steps:
       - name: Checkout craft-sdk
         uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
-        with:
-          fetch-depth: 0
 
       - name: Download craft-sdk snap
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
@@ -48,5 +46,12 @@ jobs:
 
       - name: Test the test snap
         run: |
-          sudo snap install ./test/test-python-app_0.1_amd64.snap --dangerous
-          snap run test-python-app.my-app
+          sudo snap install ./test/test-python-app*.snap --dangerous
+
+          output=$(test-python-app.my-app)
+          echo "$output"
+
+          if ! grep -q "Validation works:" <<< "$output"; then
+            echo "Error: expected 'Validation works:' in output"
+            exit 1
+          fi
